[build]
  command = "npm run build"
  publish = "dist"

# Handle all routes for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Add security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' *.googleapis.com *.gstatic.com *.google.com *.youtube.com *.ytimg.com data: blob:; img-src 'self' data: blob: *.unsplash.com *.hotel-rheinpark.de *.randomuser.me;"